## append a value in list
student = ["riju","sahu","sonia","patil"]
print(student)
print(student)
print(student)
print(student)
type(student)
len_student = len(student)
print("To find out length of student is:",len_student)
student.append("ajay")
print("After appending 'ajay' to list:", student)
print("after value added to a list, then length of student is:", len_student)
typ_student = type(student)
print(typ_student)
print ("********************************************************************************************")
dict_value = {"name": "murugan","age":"34","place":"Bangalore"}
print(dict_value)
type_dic = type(dict_value)
print(type_dic)
len_dic = len(dict_value)
print(len_dic)
print(dict_value["name"])
print ("**********************************************************************************************")
print ("**********************************************************************************************")
sport_dict = {"cricket": ["MS DHONI","RAINA","VIRAT"], "football": ["MESSI","RONALDO","SALAH"]}
print(sport_dict)
len_sport =len(sport_dict)
print(len_sport)
type_sport = type(sport_dict)
print(type_sport)
print(sport_dict["cricket"][-1])
print(sport_dict["cricket"][0])
print(sport_dict["cricket"][1])
print(sport_dict["cricket"][2])
