pipeline {
    agent any
    stages {
        stage('git checkout') {
            steps {
                echo 'Code cloing in progress'
                sh '''
                git clone https://github.com/thangacodes/python-scripts.git
            '''
            }
        }
        stage('keypair_rotation'){
            steps{
                sh '''
                cd boto3_scripts
                python3 -m venv keypair
                echo "Activating Venv in this machine..."
                source keypair/bin/activate
                pip install boto3
                python3 create_keypair.py
                sleep 10
                deactivate
            '''
            }
        }
	stage('Workspace Cleanup'){
	   steps{
	       sh '''
                    echo "Going to clean Jenkins Workspace"
                    cleanWs()
	        '''
            }
        }
    }
}
